/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ILogin {
  password: string;
  phone: string;
}

export interface ISignUp {
  password: string;
  phone: string;
  secret: string;
}
