/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IAddProductSchema {
  categoryId: string;
  img?: string;
  price: number;
  productName: string;
}

export interface IUpdateProductSchema {
  categoryId: string;
  img?: string;
  price: number;
  productId: string;
  productName: string;
}
